plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.9.20'
    id("com.github.johnrengelman.shadow") version "8.1.1"  // Add Shadow plugin
}

group 'org.ndia.products'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def ktor_version = "2.3.6"

dependencies {
    implementation("com.amazonaws:aws-lambda-java-core:1.2.2")
    implementation("com.amazonaws:aws-lambda-java-events:3.11.0")
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation("org.jetbrains.kotlin:kotlin-stdlib")
    implementation "io.ktor:ktor-client-core:$ktor_version"
    implementation "io.ktor:ktor-client-cio:$ktor_version"
    implementation "io.ktor:ktor-client-content-negotiation:$ktor_version"
    implementation("io.ktor:ktor-serialization-jackson:$ktor_version")
    implementation("org.slf4j:slf4j-api:2.0.9")
    implementation('ch.qos.logback:logback-classic:1.4.12')


}

//tasks.withType<Jar> {
//    manifest {
//        attributes["Main-Class"] = "org.ndia.products.Handler"
//    }
//}



test {
    useJUnitPlatform()
}